channel: stable
addons:
  vlc-fork:
    repository: HomeAssistant-Fork-Addons/vlc-fork
    target: vlc-fork
    image: https://github.com/scott-home/homeassistant-addons.git-{arch}
  vlc:
    repository: HomeAssistant-Fork-Addons/vlc
    target: vlc
    image: https://github.com/scott-home/homeassistant-addons.git-{arch}
